Repository dnd-side-project/dnd-8th-9-backend, pull requests merged in 2023-05, with the labels that each got.

#53 로그인 리팩토링 & 내정보 가져오기 API 추가
  .DS_Store
  build.gradle
  src/main/java/com/team9ookie/dangdo/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/team9ookie/dangdo/auth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/team9ookie/dangdo/auth/RoleType.java
  src/main/java/com/team9ookie/dangdo/auth/common/ApiResponse.java
  src/main/java/com/team9ookie/dangdo/auth/common/ApiResponseHeader.java
  src/main/java/com/team9ookie/dangdo/auth/exception/RestAuthenticationEntryPoint.java
  src/main/java/com/team9ookie/dangdo/auth/filter/TokenAuthenticationFilter.java
  src/main/java/com/team9ookie/dangdo/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/team9ookie/dangdo/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/team9ookie/dangdo/auth/handler/TokenAccessDeniedHandler.java
  src/main/java/com/team9ookie/dangdo/auth/token/AuthToken.java
  src/main/java/com/team9ookie/dangdo/auth/token/AuthTokenProvider.java
  src/main/java/com/team9ookie/dangdo/auth/util/HeaderUtil.java
  src/main/java/com/team9ookie/dangdo/config/AppProperties.java
  src/main/java/com/team9ookie/dangdo/config/JwtConfig.java
  src/main/java/com/team9ookie/dangdo/config/SecurityConfiguration.java
  src/main/java/com/team9ookie/dangdo/controller/UserController.java
  src/main/java/com/team9ookie/dangdo/entity/UserRefreshToken.java
  src/main/java/com/team9ookie/dangdo/repository/UserRefreshTokenRepository.java
  src/main/java/com/team9ookie/dangdo/service/UserService.java
  src/main/resources/application.yml
Labels: 🚀 feature, 🔨refactoring

#56 feat: Menu, User관련 피드백 반영
  src/main/java/com/team9ookie/dangdo/auth/userinfo/OAuthAttributes.java
  src/main/java/com/team9ookie/dangdo/controller/MenuController.java
  src/main/java/com/team9ookie/dangdo/controller/UserController.java
  src/main/java/com/team9ookie/dangdo/dto/menu/MenuDetailDto.java
  src/main/java/com/team9ookie/dangdo/dto/menu/MenuResponseDto.java
  src/main/java/com/team9ookie/dangdo/dto/menu/MenuResponseListDto.java
  src/main/java/com/team9ookie/dangdo/entity/Menu.java
  src/main/java/com/team9ookie/dangdo/entity/User.java
  src/main/java/com/team9ookie/dangdo/service/MenuService.java
  src/main/resources/application.yml
Labels: 🚀 feature, 🔨refactoring

#57 Feat/frontend feedback 1
  src/main/java/com/team9ookie/dangdo/config/WebConfig.java
  src/main/java/com/team9ookie/dangdo/dto/review/ReviewResponseDto.java
  src/main/java/com/team9ookie/dangdo/dto/store/StoreDetailDto.java
  src/main/java/com/team9ookie/dangdo/dto/store/StoreDto.java
  src/main/java/com/team9ookie/dangdo/dto/store/StoreRequestDto.java
  src/main/java/com/team9ookie/dangdo/dto/store/StoreResponseDto.java
  src/main/java/com/team9ookie/dangdo/entity/Store.java
  src/main/java/com/team9ookie/dangdo/repository/CustomReviewRepository.java
  src/main/java/com/team9ookie/dangdo/repository/CustomStoreRepository.java
Labels: 🚀 feature

#58 feat: 2차 피드백 반영
  src/main/java/com/team9ookie/dangdo/dto/menu/MenuResponseDto.java
  src/main/java/com/team9ookie/dangdo/dto/menu/MenuResponseListDto.java
  src/main/java/com/team9ookie/dangdo/service/MenuService.java
  src/main/resources/application.yml
Labels: 🔨refactoring

#60 Feat/frontend feedback 1
  src/main/java/com/team9ookie/dangdo/config/UserArgumentResolver.java
  src/main/java/com/team9ookie/dangdo/config/WebConfig.java
  src/main/java/com/team9ookie/dangdo/controller/MenuController.java
  src/main/java/com/team9ookie/dangdo/controller/ReviewController.java
  src/main/java/com/team9ookie/dangdo/controller/StoreController.java
  src/main/java/com/team9ookie/dangdo/controller/UserController.java
  src/main/java/com/team9ookie/dangdo/dto/review/ReviewRequestDto.java
  src/main/java/com/team9ookie/dangdo/service/ReviewService.java
Labels: 🐞bug, 🔨refactoring

#61 feat: POST /menus 수정
  src/main/java/com/team9ookie/dangdo/controller/MenuController.java
  src/main/java/com/team9ookie/dangdo/dto/menu/MenuRequestDto.java
  src/main/java/com/team9ookie/dangdo/service/MenuService.java
Labels: 🚀 feature, 🔨refactoring
